name: manual

on:
  workflow_dispatch:

jobs:
  excavate:
    name: manual update
    runs-on: ubuntu-latest
    steps:
      - name: update
        uses: ExceptionsOccur/scoop-mirror/.github/workflows/update.yml@master
